# Generated by Django 2.1.5 on 2019-01-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_studentadmission_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentadmission',
            name='batch',
        ),
    ]
