# Generated by Django 2.1.5 on 2019-01-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_remove_studentadmission_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.Course'),
        ),
    ]
