# Generated by Django 2.1.5 on 2019-01-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('theory', models.IntegerField()),
                ('practical', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='marksentry',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.ExamTerm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksentry',
            name='student_marks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.StudentMarks'),
            preserve_default=False,
        ),
    ]
