# Generated by Django 2.1.5 on 2019-01-25 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('exam', '0002_auto_20190124_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksEntryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('theory', models.IntegerField()),
                ('practical', models.IntegerField()),
                ('full_marks', models.IntegerField()),
                ('full_marks_th', models.IntegerField()),
                ('full_marks_pr', models.IntegerField()),
                ('pass_marks', models.IntegerField()),
                ('pass_marks_th', models.IntegerField()),
                ('pass_marks_pr', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='studentmarks',
            name='student',
        ),
        migrations.RemoveField(
            model_name='marksentry',
            name='full_marks',
        ),
        migrations.RemoveField(
            model_name='marksentry',
            name='full_marks_pr',
        ),
        migrations.RemoveField(
            model_name='marksentry',
            name='full_marks_th',
        ),
        migrations.RemoveField(
            model_name='marksentry',
            name='pass_marks',
        ),
        migrations.RemoveField(
            model_name='marksentry',
            name='pass_marks_pr',
        ),
        migrations.RemoveField(
            model_name='marksentry',
            name='pass_marks_th',
        ),
        migrations.RemoveField(
            model_name='marksentry',
            name='student_marks',
        ),
        migrations.DeleteModel(
            name='StudentMarks',
        ),
        migrations.AddField(
            model_name='marksentrydetail',
            name='marks_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.MarksEntry'),
        ),
        migrations.AddField(
            model_name='marksentrydetail',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
