# Generated by Django 2.1.5 on 2019-01-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20190125_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksentrydetail',
            name='discipline',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
