# Generated by Django 2.1.5 on 2019-02-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('expense_detail', models.CharField(max_length=120)),
                ('amount', models.IntegerField()),
                ('expense_date', models.DateField()),
                ('receipt_number', models.IntegerField(blank=True, null=True)),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.ExpenseCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
