# Generated by Django 2.1.5 on 2019-02-04 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20190123_0908'),
        ('accounting', '0003_feecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, null=True)),
                ('total_amount', models.IntegerField()),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Class')),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.FeeCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
